module.exports = {
  id: '001_initial_reporting_mirror',
  description: 'Create the initial MongoDB-to-SQL reporting mirror schema',
  statements: [
    `CREATE TABLE IF NOT EXISTS organizations (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      name VARCHAR(255) NOT NULL,
      slug VARCHAR(160) NOT NULL,
      status VARCHAR(32) NOT NULL,
      security_policy_json JSON NULL,
      source_created_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_organizations_mongo_id (mongo_id),
      UNIQUE KEY uq_organizations_slug (slug),
      KEY ix_organizations_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_series (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      organization_id BIGINT UNSIGNED NOT NULL,
      name VARCHAR(255) NOT NULL,
      slug VARCHAR(160) NOT NULL,
      status VARCHAR(32) NOT NULL,
      default_linking_mode VARCHAR(32) NOT NULL,
      source_created_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_event_series_mongo_id (mongo_id),
      UNIQUE KEY uq_event_series_org_slug (organization_id, slug),
      KEY ix_event_series_status (status),
      CONSTRAINT fk_event_series_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS events (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      organization_id BIGINT UNSIGNED NOT NULL,
      series_id BIGINT UNSIGNED NOT NULL,
      name VARCHAR(255) NOT NULL,
      slug VARCHAR(160) NOT NULL,
      event_year VARCHAR(16) NOT NULL,
      status VARCHAR(32) NOT NULL,
      starts_at DATETIME(3) NULL,
      ends_at DATETIME(3) NULL,
      timezone VARCHAR(80) NOT NULL DEFAULT 'Asia/Bangkok',
      linking_mode VARCHAR(32) NOT NULL,
      archived_at DATETIME(3) NULL,
      activated_at DATETIME(3) NULL,
      source_created_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_events_mongo_id (mongo_id),
      UNIQUE KEY uq_events_org_series_slug (organization_id, series_id, slug),
      KEY ix_events_org_year (organization_id, event_year),
      KEY ix_events_status (status),
      CONSTRAINT fk_events_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
      CONSTRAINT fk_events_series FOREIGN KEY (series_id) REFERENCES event_series (id) ON DELETE RESTRICT,
      CONSTRAINT ck_events_date_range CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS participants_core (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      organization_id BIGINT UNSIGNED NULL,
      series_id BIGINT UNSIGNED NULL,
      event_id BIGINT UNSIGNED NULL,
      event_year VARCHAR(16) NOT NULL DEFAULT '',
      qr_code VARCHAR(255) NOT NULL,
      status VARCHAR(32) NOT NULL,
      registration_type VARCHAR(32) NOT NULL,
      registered_point_name VARCHAR(255) NOT NULL DEFAULT '',
      followers INT UNSIGNED NOT NULL DEFAULT 0,
      consent_status VARCHAR(32) NULL,
      email_blind_index CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      phone_blind_index CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      name_blind_index CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      line_user_blind_index CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      is_line_linked BOOLEAN NOT NULL DEFAULT FALSE,
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
      is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
      registered_at DATETIME(3) NULL,
      checked_in_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_participants_core_mongo_id (mongo_id),
      UNIQUE KEY uq_participants_core_qr_code (qr_code),
      KEY ix_participants_event_status (event_id, status),
      KEY ix_participants_event_registered (event_id, registered_at),
      KEY ix_participants_email_hash (event_id, email_blind_index),
      CONSTRAINT fk_participants_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
      CONSTRAINT fk_participants_series FOREIGN KEY (series_id) REFERENCES event_series (id) ON DELETE RESTRICT,
      CONSTRAINT fk_participants_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT ck_participants_followers CHECK (followers >= 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS wallets (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      participant_id BIGINT UNSIGNED NOT NULL,
      event_id BIGINT UNSIGNED NULL,
      event_year VARCHAR(16) NOT NULL DEFAULT '',
      event_scope_key VARCHAR(80) NOT NULL,
      coin_balance BIGINT UNSIGNED NOT NULL DEFAULT 0,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      source_created_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_wallets_mongo_id (mongo_id),
      UNIQUE KEY uq_wallets_participant_scope (participant_id, event_scope_key),
      KEY ix_wallets_event (event_id),
      CONSTRAINT fk_wallets_participant FOREIGN KEY (participant_id) REFERENCES participants_core (id) ON DELETE RESTRICT,
      CONSTRAINT fk_wallets_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT ck_wallets_balance CHECK (coin_balance >= 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS wallet_coupons (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      wallet_id BIGINT UNSIGNED NOT NULL,
      coupon_id VARCHAR(160) NOT NULL,
      name VARCHAR(255) NOT NULL,
      quantity BIGINT UNSIGNED NOT NULL DEFAULT 0,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      PRIMARY KEY (id),
      UNIQUE KEY uq_wallet_coupons_wallet_coupon (wallet_id, coupon_id),
      CONSTRAINT fk_wallet_coupons_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (id) ON DELETE CASCADE,
      CONSTRAINT ck_wallet_coupons_quantity CHECK (quantity >= 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS vendors (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      event_id BIGINT UNSIGNED NULL,
      event_year VARCHAR(16) NOT NULL DEFAULT '',
      name VARCHAR(255) NOT NULL,
      qr_code_id VARCHAR(255) NOT NULL,
      pricing_mode VARCHAR(32) NOT NULL,
      fixed_price BIGINT UNSIGNED NULL,
      min_amount BIGINT UNSIGNED NOT NULL DEFAULT 1,
      max_amount BIGINT UNSIGNED NULL,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      source_created_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_vendors_mongo_id (mongo_id),
      UNIQUE KEY uq_vendors_qr_code_id (qr_code_id),
      KEY ix_vendors_event_active (event_id, is_active),
      CONSTRAINT fk_vendors_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT ck_vendors_amount_range CHECK (max_amount IS NULL OR max_amount >= min_amount)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS vendor_menu_items (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      vendor_id BIGINT UNSIGNED NOT NULL,
      source_index INT UNSIGNED NOT NULL,
      item_id VARCHAR(160) NOT NULL,
      name VARCHAR(255) NOT NULL,
      price BIGINT UNSIGNED NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      PRIMARY KEY (id),
      UNIQUE KEY uq_vendor_menu_items_vendor_item (vendor_id, item_id),
      UNIQUE KEY uq_vendor_menu_items_source (vendor_id, source_index),
      CONSTRAINT fk_vendor_menu_items_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE CASCADE,
      CONSTRAINT ck_vendor_menu_items_price CHECK (price >= 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS wallet_transactions (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      wallet_id BIGINT UNSIGNED NOT NULL,
      vendor_id BIGINT UNSIGNED NOT NULL,
      event_id BIGINT UNSIGNED NULL,
      guest_token_mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      reversal_of_mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      reversal_of_id BIGINT UNSIGNED NULL,
      transaction_type VARCHAR(32) NOT NULL,
      idempotency_key VARCHAR(255) NULL,
      payment_method VARCHAR(32) NOT NULL,
      amount BIGINT UNSIGNED NOT NULL,
      coupon_id VARCHAR(160) NULL,
      menu_item_id VARCHAR(160) NULL,
      menu_item_name VARCHAR(255) NOT NULL DEFAULT '',
      status VARCHAR(32) NOT NULL,
      balance_before BIGINT NULL,
      balance_after BIGINT NULL,
      item_balance_before BIGINT NULL,
      item_balance_after BIGINT NULL,
      verification_code VARCHAR(80) NOT NULL DEFAULT '',
      server_time DATETIME(3) NOT NULL,
      slip_expires_at DATETIME(3) NULL,
      source_created_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_wallet_transactions_mongo_id (mongo_id),
      UNIQUE KEY uq_wallet_transactions_idempotency (wallet_id, idempotency_key),
      KEY ix_wallet_transactions_event_vendor_time (event_id, vendor_id, server_time),
      KEY ix_wallet_transactions_status_time (status, server_time),
      CONSTRAINT fk_wallet_transactions_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (id) ON DELETE RESTRICT,
      CONSTRAINT fk_wallet_transactions_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE RESTRICT,
      CONSTRAINT fk_wallet_transactions_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT fk_wallet_transactions_reversal FOREIGN KEY (reversal_of_id) REFERENCES wallet_transactions (id) ON DELETE RESTRICT,
      CONSTRAINT ck_wallet_transactions_amount CHECK (amount > 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS receipts (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      receipt_number VARCHAR(120) NOT NULL,
      participant_id BIGINT UNSIGNED NOT NULL,
      event_id BIGINT UNSIGNED NOT NULL,
      amount DECIMAL(14,2) NOT NULL,
      details_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      issued_at DATETIME(3) NOT NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_receipts_mongo_id (mongo_id),
      UNIQUE KEY uq_receipts_number (receipt_number),
      UNIQUE KEY uq_receipts_participant_event (participant_id, event_id),
      KEY ix_receipts_event_issued (event_id, issued_at),
      CONSTRAINT fk_receipts_participant FOREIGN KEY (participant_id) REFERENCES participants_core (id) ON DELETE RESTRICT,
      CONSTRAINT fk_receipts_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT ck_receipts_amount CHECK (amount >= 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS donation_summaries (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      organization_id BIGINT UNSIGNED NULL,
      series_id BIGINT UNSIGNED NULL,
      event_id BIGINT UNSIGNED NULL,
      event_year VARCHAR(16) NOT NULL DEFAULT '',
      amount DECIMAL(14,2) NOT NULL,
      transfer_at DATETIME(3) NOT NULL,
      source VARCHAR(32) NOT NULL,
      is_package BOOLEAN NOT NULL DEFAULT FALSE,
      package_type VARCHAR(160) NOT NULL DEFAULT '',
      pickup_method VARCHAR(32) NOT NULL DEFAULT '',
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
      source_created_at DATETIME(3) NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_donation_summaries_mongo_id (mongo_id),
      KEY ix_donations_event_transfer (event_id, transfer_at),
      CONSTRAINT fk_donations_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
      CONSTRAINT fk_donations_series FOREIGN KEY (series_id) REFERENCES event_series (id) ON DELETE RESTRICT,
      CONSTRAINT fk_donations_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT ck_donations_amount CHECK (amount > 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS packages (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      organization_id BIGINT UNSIGNED NULL,
      series_id BIGINT UNSIGNED NULL,
      event_id BIGINT UNSIGNED NULL,
      event_year VARCHAR(16) NOT NULL DEFAULT '',
      name VARCHAR(255) NOT NULL,
      description TEXT NULL,
      price DECIMAL(14,2) NOT NULL,
      order_deadline DATETIME(3) NULL,
      is_delivery_available BOOLEAN NOT NULL DEFAULT TRUE,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      deleted_at DATETIME(3) NULL,
      source_created_at DATETIME(3) NULL,
      mirrored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_packages_mongo_id (mongo_id),
      KEY ix_packages_event_active (event_id, is_active),
      CONSTRAINT fk_packages_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
      CONSTRAINT fk_packages_series FOREIGN KEY (series_id) REFERENCES event_series (id) ON DELETE RESTRICT,
      CONSTRAINT fk_packages_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT ck_packages_price CHECK (price >= 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS package_items (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      package_id BIGINT UNSIGNED NOT NULL,
      source_index INT UNSIGNED NOT NULL,
      item_name VARCHAR(255) NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uq_package_items_source (package_id, source_index),
      CONSTRAINT fk_package_items_package FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS package_variants (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      package_item_id BIGINT UNSIGNED NOT NULL,
      source_index INT UNSIGNED NOT NULL,
      size_label VARCHAR(120) NOT NULL,
      stock BIGINT NOT NULL DEFAULT 0,
      sold BIGINT NOT NULL DEFAULT 0,
      PRIMARY KEY (id),
      UNIQUE KEY uq_package_variants_source (package_item_id, source_index),
      CONSTRAINT fk_package_variants_item FOREIGN KEY (package_item_id) REFERENCES package_items (id) ON DELETE CASCADE,
      CONSTRAINT ck_package_variants_stock CHECK (stock >= 0),
      CONSTRAINT ck_package_variants_sold CHECK (sold >= 0 AND sold <= stock)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS mirror_backfill_checkpoints (
      domain_name VARCHAR(80) NOT NULL,
      run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      mapper_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      high_watermark_mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      last_mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      processed_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
      last_source_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      source_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      completed_at DATETIME(3) NULL,
      updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
      PRIMARY KEY (domain_name)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  ],
};
