module.exports = {
  id: '003_event_registration_primary_schema',
  description: 'Create primary-ready SQL tables for event registration cutover',
  statements: [
    `CREATE TABLE IF NOT EXISTS event_runtime_configs (
      event_id BIGINT UNSIGNED NOT NULL,
      public_links_json JSON NULL,
      branding_json JSON NULL,
      enabled_features_json JSON NULL,
      registration_config_json JSON NULL,
      layout_registration_form_json JSON NULL,
      templates_json JSON NULL,
      source_updated_at DATETIME(3) NULL,
      migrated_at DATETIME(3) NULL,
      updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
      PRIMARY KEY (event_id),
      CONSTRAINT fk_event_runtime_configs_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_registration_points (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      organization_id BIGINT UNSIGNED NULL,
      series_id BIGINT UNSIGNED NULL,
      event_id BIGINT UNSIGNED NOT NULL,
      event_year VARCHAR(16) NOT NULL DEFAULT '',
      name VARCHAR(255) NOT NULL,
      description TEXT NULL,
      point_type VARCHAR(32) NOT NULL,
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      allowed_staff_mongo_ids_json JSON NULL,
      device_ids_json JSON NULL,
      kiosk_policy_json JSON NULL,
      source_created_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      migrated_at DATETIME(3) NULL,
      created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
      PRIMARY KEY (id),
      UNIQUE KEY uq_event_registration_points_mongo (mongo_id),
      UNIQUE KEY uq_event_registration_points_event_name (event_id, name),
      KEY ix_event_registration_points_event_enabled_type (event_id, enabled, point_type),
      KEY ix_event_registration_points_event_year (event_year, enabled, point_type),
      CONSTRAINT fk_event_registration_points_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_registration_points_series FOREIGN KEY (series_id) REFERENCES event_series (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_registration_points_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT ck_event_registration_points_type CHECK (point_type IN ('onsite', 'meeting', 'kiosk', 'self_register', 'checkin', 'other'))
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_participant_fields (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      organization_id BIGINT UNSIGNED NULL,
      series_id BIGINT UNSIGNED NULL,
      event_id BIGINT UNSIGNED NOT NULL,
      event_year VARCHAR(16) NOT NULL DEFAULT '',
      field_name VARCHAR(160) NOT NULL,
      label VARCHAR(255) NOT NULL,
      field_type VARCHAR(32) NOT NULL,
      required BOOLEAN NOT NULL DEFAULT FALSE,
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      display_order INT NOT NULL DEFAULT 0,
      options_json JSON NULL,
      source_updated_at DATETIME(3) NULL,
      migrated_at DATETIME(3) NULL,
      created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
      PRIMARY KEY (id),
      UNIQUE KEY uq_event_participant_fields_mongo (mongo_id),
      UNIQUE KEY uq_event_participant_fields_event_name (event_id, field_name),
      KEY ix_event_participant_fields_event_enabled_order (event_id, enabled, display_order),
      KEY ix_event_participant_fields_event_year (event_year, enabled, display_order),
      CONSTRAINT fk_event_participant_fields_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_participant_fields_series FOREIGN KEY (series_id) REFERENCES event_series (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_participant_fields_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT ck_event_participant_fields_type CHECK (field_type IN ('text', 'email', 'number', 'select', 'date', 'phone'))
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_registrations (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      organization_id BIGINT UNSIGNED NULL,
      series_id BIGINT UNSIGNED NULL,
      event_id BIGINT UNSIGNED NOT NULL,
      event_year VARCHAR(16) NOT NULL DEFAULT '',
      qr_code_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      qr_code_ciphertext VARBINARY(2048) NULL,
      certificate_verification_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      certificate_verification_ciphertext VARBINARY(2048) NULL,
      status VARCHAR(32) NOT NULL DEFAULT 'registered',
      registration_type VARCHAR(32) NOT NULL DEFAULT 'online',
      registered_point_id BIGINT UNSIGNED NULL,
      registered_point_name VARCHAR(255) NOT NULL DEFAULT '',
      registered_by_mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      followers INT UNSIGNED NOT NULL DEFAULT 0,
      consent_status VARCHAR(32) NULL,
      special_assistance_ciphertext VARBINARY(8192) NULL,
      field_payload_json JSON NULL,
      secure_index_json JSON NULL,
      secure_search_json JSON NULL,
      email_blind_index CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      phone_blind_index CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      name_blind_index CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      line_user_blind_index CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      auth_provider VARCHAR(32) NOT NULL DEFAULT 'email',
      auth_providers_json JSON NULL,
      primary_auth_provider VARCHAR(32) NOT NULL DEFAULT 'email',
      is_line_linked BOOLEAN NOT NULL DEFAULT FALSE,
      line_profile_ciphertext VARBINARY(8192) NULL,
      notification_preferences_json JSON NULL,
      trusted_devices_json JSON NULL,
      tags_json JSON NULL,
      participant_token_version INT UNSIGNED NOT NULL DEFAULT 0,
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
      is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
      is_forfeited BOOLEAN NOT NULL DEFAULT FALSE,
      registered_at DATETIME(3) NULL,
      checked_in_at DATETIME(3) NULL,
      last_login_at DATETIME(3) NULL,
      deleted_at DATETIME(3) NULL,
      revoked_at DATETIME(3) NULL,
      source_created_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      migrated_at DATETIME(3) NULL,
      created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
      PRIMARY KEY (id),
      UNIQUE KEY uq_event_registrations_mongo (mongo_id),
      UNIQUE KEY uq_event_registrations_qr_hash (qr_code_hash),
      UNIQUE KEY uq_event_registrations_cert_hash (certificate_verification_hash),
      KEY ix_event_registrations_event_status (event_id, status, is_deleted),
      KEY ix_event_registrations_event_registered (event_id, registered_at),
      KEY ix_event_registrations_event_checked_in (event_id, checked_in_at),
      KEY ix_event_registrations_event_type (event_id, registration_type),
      KEY ix_event_registrations_event_point (event_id, registered_point_id),
      KEY ix_event_registrations_email (event_id, email_blind_index),
      KEY ix_event_registrations_phone (event_id, phone_blind_index),
      KEY ix_event_registrations_name (event_id, name_blind_index),
      CONSTRAINT fk_event_registrations_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_registrations_series FOREIGN KEY (series_id) REFERENCES event_series (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_registrations_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_registrations_point FOREIGN KEY (registered_point_id) REFERENCES event_registration_points (id) ON DELETE RESTRICT,
      CONSTRAINT ck_event_registrations_status CHECK (status IN ('registered', 'checkedIn', 'cancelled')),
      CONSTRAINT ck_event_registrations_type CHECK (registration_type IN ('online', 'onsite', 'onsite_staff', 'onsite_kiosk', 'self_register')),
      CONSTRAINT ck_event_registrations_followers CHECK (followers >= 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_registration_field_values (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      participant_id BIGINT UNSIGNED NOT NULL,
      field_id BIGINT UNSIGNED NOT NULL,
      event_id BIGINT UNSIGNED NOT NULL,
      field_name VARCHAR(160) NOT NULL,
      value_type VARCHAR(32) NOT NULL DEFAULT 'text',
      value_ciphertext VARBINARY(8192) NULL,
      value_json JSON NULL,
      value_blind_index CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      value_search_json JSON NULL,
      updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
      PRIMARY KEY (id),
      UNIQUE KEY uq_event_registration_field_values_participant_field (participant_id, field_id),
      KEY ix_event_registration_field_values_event_field (event_id, field_name),
      KEY ix_event_registration_field_values_blind_index (event_id, field_name, value_blind_index),
      CONSTRAINT fk_event_registration_field_values_participant FOREIGN KEY (participant_id) REFERENCES event_registrations (id) ON DELETE CASCADE,
      CONSTRAINT fk_event_registration_field_values_field FOREIGN KEY (field_id) REFERENCES event_participant_fields (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_registration_field_values_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_registration_idempotency_keys (
      event_id BIGINT UNSIGNED NOT NULL,
      key_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      fingerprint_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      participant_id BIGINT UNSIGNED NULL,
      request_scope VARCHAR(80) NOT NULL DEFAULT 'participant-registration',
      first_seen_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      last_replayed_at DATETIME(3) NULL,
      replay_count INT UNSIGNED NOT NULL DEFAULT 0,
      PRIMARY KEY (event_id, key_hash),
      KEY ix_event_registration_idempotency_participant (participant_id),
      CONSTRAINT fk_event_registration_idempotency_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_registration_idempotency_participant FOREIGN KEY (participant_id) REFERENCES event_registrations (id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_registration_checkins (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      event_id BIGINT UNSIGNED NOT NULL,
      participant_id BIGINT UNSIGNED NOT NULL,
      registration_point_id BIGINT UNSIGNED NULL,
      checked_in_by_mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      device_id VARCHAR(190) NULL,
      source_scope VARCHAR(64) NOT NULL DEFAULT 'staff',
      result VARCHAR(32) NOT NULL DEFAULT 'success',
      previous_status VARCHAR(32) NULL,
      followers INT UNSIGNED NULL,
      checked_in_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      PRIMARY KEY (id),
      UNIQUE KEY uq_event_registration_checkins_migrated_once (participant_id, checked_in_at, source_scope),
      KEY ix_event_registration_checkins_event_time (event_id, checked_in_at),
      KEY ix_event_registration_checkins_participant (participant_id, checked_in_at),
      KEY ix_event_registration_checkins_point (registration_point_id, checked_in_at),
      CONSTRAINT fk_event_registration_checkins_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_registration_checkins_participant FOREIGN KEY (participant_id) REFERENCES event_registrations (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_registration_checkins_point FOREIGN KEY (registration_point_id) REFERENCES event_registration_points (id) ON DELETE RESTRICT,
      CONSTRAINT ck_event_registration_checkins_result CHECK (result IN ('success', 'already_checked_in', 'not_found', 'rejected')),
      CONSTRAINT ck_event_registration_checkins_followers CHECK (followers IS NULL OR followers >= 0)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_scoped_registration_sessions (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      jti_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      scope VARCHAR(80) NOT NULL,
      event_id BIGINT UNSIGNED NOT NULL,
      event_year VARCHAR(16) NOT NULL DEFAULT '',
      point_id BIGINT UNSIGNED NOT NULL,
      staff_mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      participant_id BIGINT UNSIGNED NULL,
      used_at DATETIME(3) NULL,
      expires_at DATETIME(3) NOT NULL,
      source_created_at DATETIME(3) NULL,
      source_updated_at DATETIME(3) NULL,
      migrated_at DATETIME(3) NULL,
      created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
      PRIMARY KEY (id),
      UNIQUE KEY uq_event_scoped_sessions_jti_hash (jti_hash),
      KEY ix_event_scoped_sessions_event_point (event_id, point_id, expires_at),
      KEY ix_event_scoped_sessions_expires (expires_at),
      KEY ix_event_scoped_sessions_participant (participant_id),
      CONSTRAINT fk_event_scoped_sessions_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_scoped_sessions_point FOREIGN KEY (point_id) REFERENCES event_registration_points (id) ON DELETE RESTRICT,
      CONSTRAINT fk_event_scoped_sessions_participant FOREIGN KEY (participant_id) REFERENCES event_registrations (id) ON DELETE SET NULL,
      CONSTRAINT ck_event_scoped_sessions_scope CHECK (scope IN ('self_register_session'))
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_registration_reconciliation_snapshots (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      event_id BIGINT UNSIGNED NOT NULL,
      run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      snapshot_type VARCHAR(64) NOT NULL,
      source_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
      sql_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
      source_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      sql_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      mismatch_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
      detail_json JSON NULL,
      created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      PRIMARY KEY (id),
      UNIQUE KEY uq_event_registration_recon_run_type (run_id, snapshot_type),
      KEY ix_event_registration_recon_event_time (event_id, created_at),
      CONSTRAINT fk_event_registration_recon_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS event_registration_cutover_runs (
      run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      event_id BIGINT UNSIGNED NULL,
      mongo_event_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      phase VARCHAR(64) NOT NULL,
      status VARCHAR(32) NOT NULL,
      started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      completed_at DATETIME(3) NULL,
      source_high_watermark_mongo_id CHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
      source_counts_json JSON NULL,
      sql_counts_json JSON NULL,
      source_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      sql_checksum CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      blockers_json JSON NULL,
      note TEXT NULL,
      PRIMARY KEY (run_id),
      KEY ix_event_registration_cutover_event_phase (event_id, phase, status),
      KEY ix_event_registration_cutover_status (status, started_at),
      CONSTRAINT fk_event_registration_cutover_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT,
      CONSTRAINT ck_event_registration_cutover_status CHECK (status IN ('planned', 'running', 'passed', 'failed', 'rolled_back'))
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  ],
};
